#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamHangman.Resource", IsApplication=true)]

namespace XamHangman
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int coins_256 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int hangman0 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int hangman1 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int hangman10 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int hangman2 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int hangman3 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int hangman4 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int hangman5 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int hangman6 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int hangman7 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int hangman8 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int hangman9 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int ic_baseline_account_box_24dp = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int ic_baseline_monetization_on_24dp = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int ic_dashboard_black_24dp = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int ic_home_black_24dp = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int ic_notifications_black_24dp = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int ic_round_leaderboard_black_24dp = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int ic_round_play_arrow_24dp = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int loses_256 = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int wins_256 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int xp_256 = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int btnA = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int btnB = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int btnC = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int btnD = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int btnE = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int btnF = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int btnG = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int btnH = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int btnI = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int btnJ = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int btnK = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int btnL = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int btnM = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int btnN = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int btnO = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int btnP = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int btnPlay = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int btnQ = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int btnR = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int btnReset = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int btnS = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int btnT = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int btnU = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int btnV = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int btnW = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int btnX = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int btnY = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int btnZ = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int imageView1 = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int imageView2 = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int imgHangman = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int leaderboard_txtLoses = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int leaderboard_txtUsername = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int leaderboard_txtWins = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int linearLayout1 = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int lstLeaderboard = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int navigation = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int navigation_leaderboard = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int navigation_play = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int navigation_profile = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int textView1 = 2130903080;
			
			// aapt resource value: 0x7F03002E
			public const int txtUsername = 2130903086;
			
			// aapt resource value: 0x7F030029
			public const int txtUserProfile_Coins = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int txtUserProfile_Loses = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int txtUserProfile_Name = 2130903083;
			
			// aapt resource value: 0x7F03002C
			public const int txtUserProfile_Wins = 2130903084;
			
			// aapt resource value: 0x7F03002D
			public const int txtUserProfile_XP = 2130903085;
			
			// aapt resource value: 0x7F03002F
			public const int txtWinLose = 2130903087;
			
			// aapt resource value: 0x7F030030
			public const int txtWord = 2130903088;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040001
			public const int activity_gameplay = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int activity_home = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int activity_leaderboard = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int activity_localprofile = 2130968580;
			
			// aapt resource value: 0x7F040000
			public const int LeaderboardItem = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F050000
			public const int navigation = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int ic_launcher = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int ic_launcher_foreground = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int ic_launcher_round = 2131099650;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int a = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int action_settings = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int app_name = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int b = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int c = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int d = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int e = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int f = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int filler = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int g = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int h = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int hangman = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int i = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int j = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int k = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int l = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int leaderboard_loses = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int leaderboard_name = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int leaderboard_wins = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int m = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int n = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int o = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int p = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int play = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int q = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int r = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int reset = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int s = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int space = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int t = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int title_leaderboard = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int title_play = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int title_profile = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int txtUsername_Hint = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int u = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int v = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int w = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int welcomeMsg = 2131165221;
			
			// aapt resource value: 0x7F070026
			public const int word = 2131165222;
			
			// aapt resource value: 0x7F070027
			public const int x = 2131165223;
			
			// aapt resource value: 0x7F070028
			public const int y = 2131165224;
			
			// aapt resource value: 0x7F070029
			public const int z = 2131165225;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int AppTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
